/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ufms.facom.apsoo.sysconsorcio.view;

import javax.swing.JOptionPane;

/**
 *
 * @author joshua
 */
public class VendaView extends javax.swing.JPanel {
    
    private int acao;

    /**
     * Creates new form ViewVendas
     */
    public VendaView() {
        initComponents();
        
        acao = 0; //iniciar
    }

    public int getAcao() {
        return acao;
    }
    
    public void iniciarView() {
        acao = 1; //iniciado

        jButtonConsultar.setEnabled(true);
        jButtonInserir.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldCodigoAdmin.setText("");
        jTextFieldCodigoCliente.setText("");
        jTextFieldCodigoModelo.setText("");
        jTextFieldCodigoVenda.setText("");
        jTextFieldCodigoVendedor.setText("");
        jTextFieldCota.setText("");
        jTextFieldDataCadastral.setText("");
        jTextFieldDataEntrada.setText("");
        jTextFieldDataInicioVigencia.setText("");
        jTextFieldGrupo.setText("");
        jTextFieldNomeAdmin.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldNomeModelo.setText("");
        jTextFieldNomeVendedor.setText("");
        jTextFieldNumeroContrato.setText("");
        jTextFieldObservacao.setText("");
        jTextFieldQuantidadeParcela.setText("");
        jTextFieldValorBem.setText("");
        jTextFieldValorEntrada.setText("");

        jTextFieldCodigoAdmin.setEnabled(false);
        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldCodigoModelo.setEnabled(false);
        jTextFieldCodigoVenda.setEnabled(false);
        jTextFieldCodigoVendedor.setEnabled(false);
        jTextFieldCota.setEnabled(false);
        jTextFieldDataCadastral.setEnabled(false);
        jTextFieldDataEntrada.setEnabled(false);
        jTextFieldDataInicioVigencia.setEnabled(false);
        jTextFieldGrupo.setEnabled(false);
        jTextFieldNomeAdmin.setEnabled(false);
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldNomeModelo.setEnabled(false);
        jTextFieldNomeVendedor.setEnabled(false);
        jTextFieldNumeroContrato.setEnabled(false);
        jTextFieldObservacao.setEnabled(false);
        jTextFieldQuantidadeParcela.setEnabled(false);
        jTextFieldValorBem.setEnabled(false);
        jTextFieldValorEntrada.setEnabled(false);

        setVisible(true);
    }

    public void sairView() {
        acao = 0; //iniciar
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultar = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jTextFieldCodigoVenda = new javax.swing.JTextField();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jTextFieldCodigoAdmin = new javax.swing.JTextField();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldNomeAdmin = new javax.swing.JTextField();
        jLabelVenda = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelAdmin = new javax.swing.JLabel();
        jTextFieldNomeVendedor = new javax.swing.JTextField();
        jTextFieldCodigoVendedor = new javax.swing.JTextField();
        jLabelVendedor = new javax.swing.JLabel();
        jTextFieldDataCadastral = new javax.swing.JTextField();
        jLabelDataCadastral = new javax.swing.JLabel();
        jLabelNumeroContrato = new javax.swing.JLabel();
        jTextFieldNumeroContrato = new javax.swing.JTextField();
        jTextFieldDataInicioVigencia = new javax.swing.JTextField();
        jTextFieldQuantidadeParcela = new javax.swing.JTextField();
        jTextFieldGrupo = new javax.swing.JTextField();
        jTextFieldCota = new javax.swing.JTextField();
        jTextFieldObservacao = new javax.swing.JTextField();
        jTextFieldCodigoModelo = new javax.swing.JTextField();
        jTextFieldNomeModelo = new javax.swing.JTextField();
        jTextFieldValorBem = new javax.swing.JTextField();
        jTextFieldValorEntrada = new javax.swing.JTextField();
        jTextFieldDataEntrada = new javax.swing.JTextField();
        jLabelDataEntrada = new javax.swing.JLabel();
        jLabelValorEntrada = new javax.swing.JLabel();
        jLabelValorBem = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelObservacao = new javax.swing.JLabel();
        jLabelDataInicioVigencia = new javax.swing.JLabel();
        jLabelQuatidadeParcela = new javax.swing.JLabel();
        jLabelGrupo = new javax.swing.JLabel();
        jLabelCota = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        jButtonConsultar.setLabel("Consultar");
        jButtonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarMouseClicked(evt);
            }
        });

        jButtonInserir.setText("Inserir");
        jButtonInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInserirMouseClicked(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlterarMouseClicked(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseClicked(evt);
            }
        });

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmarMouseClicked(evt);
            }
        });

        jTextFieldCodigoVenda.setColumns(10);

        jTextFieldCodigoCliente.setColumns(10);

        jTextFieldCodigoAdmin.setColumns(10);

        jTextFieldNomeCliente.setColumns(40);

        jTextFieldNomeAdmin.setColumns(40);

        jLabelVenda.setText("Código");

        jLabelCliente.setText("Cliente");

        jLabelAdmin.setText("Administradora");

        jTextFieldNomeVendedor.setColumns(40);

        jTextFieldCodigoVendedor.setColumns(10);

        jLabelVendedor.setText("Vendedor");

        jTextFieldDataCadastral.setColumns(10);

        jLabelDataCadastral.setText("Data Cadastral");

        jLabelNumeroContrato.setText("Nº. Contrato");

        jTextFieldNumeroContrato.setColumns(15);

        jTextFieldDataInicioVigencia.setColumns(10);

        jTextFieldQuantidadeParcela.setColumns(10);

        jTextFieldGrupo.setColumns(10);

        jTextFieldCota.setColumns(10);

        jTextFieldObservacao.setColumns(30);

        jTextFieldCodigoModelo.setColumns(10);

        jTextFieldNomeModelo.setColumns(20);

        jTextFieldValorBem.setColumns(15);

        jTextFieldValorEntrada.setColumns(15);

        jTextFieldDataEntrada.setColumns(10);

        jLabelDataEntrada.setText("Data Entrada");

        jLabelValorEntrada.setText("Valor Entrada");

        jLabelValorBem.setText("Valor do Bem");

        jLabelModelo.setText("Modelo");

        jLabelObservacao.setText("Obs.");

        jLabelDataInicioVigencia.setText("Dt. Início Vigência");

        jLabelQuatidadeParcela.setText("Qtde. Parcelas");

        jLabelGrupo.setText("Grupo");

        jLabelCota.setText("Cota");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNumeroContrato)
                            .addComponent(jLabelVenda)
                            .addComponent(jLabelCliente)
                            .addComponent(jLabelAdmin)
                            .addComponent(jLabelVendedor)
                            .addComponent(jLabelDataInicioVigencia)
                            .addComponent(jLabelQuatidadeParcela)
                            .addComponent(jLabelGrupo)
                            .addComponent(jLabelCota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDataCadastral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDataCadastral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDataInicioVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldQuantidadeParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelValorBem, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelValorEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDataEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelObservacao, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldValorBem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCodigoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNomeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonInserir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVenda)
                    .addComponent(jTextFieldDataCadastral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataCadastral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroContrato)
                    .addComponent(jTextFieldNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDataInicioVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataInicioVigencia))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelValorEntrada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQuantidadeParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelQuatidadeParcela))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldValorBem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelValorBem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGrupo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCota)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelObservacao))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jButtonConsultar.getAccessibleContext().setAccessibleName("jButtonConsultar");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        // TODO add your handling code here:
        iniciarView();
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarMouseClicked
        // TODO add your handling code here:
        acao = 2; //consultar

        jButtonConsultar.setEnabled(false);
        jButtonInserir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonConfirmar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldCodigoAdmin.setEnabled(true);
        jTextFieldCodigoCliente.setEnabled(true);
        jTextFieldCodigoModelo.setEnabled(false);
        jTextFieldCodigoVenda.setEnabled(true);
        jTextFieldCodigoVendedor.setEnabled(true);
        jTextFieldCota.setEnabled(true);
        jTextFieldDataCadastral.setEnabled(true);
        jTextFieldDataEntrada.setEnabled(false);
        jTextFieldDataInicioVigencia.setEnabled(false);
        jTextFieldGrupo.setEnabled(true);
        jTextFieldNomeAdmin.setEnabled(true);
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldNomeModelo.setEnabled(false);
        jTextFieldNomeVendedor.setEnabled(true);
        jTextFieldNumeroContrato.setEnabled(true);
        jTextFieldObservacao.setEnabled(false);
        jTextFieldQuantidadeParcela.setEnabled(false);
        jTextFieldValorBem.setEnabled(false);
        jTextFieldValorEntrada.setEnabled(false);
    }//GEN-LAST:event_jButtonConsultarMouseClicked

    private void jButtonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmarMouseClicked
        // TODO add your handling code here:
        switch (acao) {
            case 2:
                acao = 3; //consultado
                
                jButtonConsultar.setEnabled(false);
                jButtonInserir.setEnabled(true);
                jButtonAlterar.setEnabled(true);
                jButtonExcluir.setEnabled(true);
                jButtonConfirmar.setEnabled(true);
                jButtonCancelar.setEnabled(true);
                
                // ler dados
                ConsultaVendaView cvv = new ConsultaVendaView(null, true);

                cvv.setVisible(true);
                
                JOptionPane.showMessageDialog(null, "teste");
                
                jTextFieldCodigoAdmin.setEnabled(true);
                jTextFieldCodigoCliente.setEnabled(true);
                jTextFieldCodigoModelo.setEnabled(true);
                jTextFieldCodigoVenda.setEnabled(true);
                jTextFieldCodigoVendedor.setEnabled(true);
                jTextFieldCota.setEnabled(true);
                jTextFieldDataCadastral.setEnabled(true);
                jTextFieldDataEntrada.setEnabled(true);
                jTextFieldDataInicioVigencia.setEnabled(true);
                jTextFieldGrupo.setEnabled(true);
                jTextFieldNomeAdmin.setEnabled(true);
                jTextFieldNomeCliente.setEnabled(true);
                jTextFieldNomeModelo.setEnabled(true);
                jTextFieldNomeVendedor.setEnabled(true);
                jTextFieldNumeroContrato.setEnabled(true);
                jTextFieldObservacao.setEnabled(true);
                jTextFieldQuantidadeParcela.setEnabled(true);
                jTextFieldValorBem.setEnabled(true);
                jTextFieldValorEntrada.setEnabled(true);

                jTextFieldCodigoAdmin.setEditable(false);
                jTextFieldCodigoCliente.setEditable(false);
                jTextFieldCodigoModelo.setEditable(false);
                jTextFieldCodigoVenda.setEditable(false);
                jTextFieldCodigoVendedor.setEditable(false);
                jTextFieldCota.setEditable(false);
                jTextFieldDataCadastral.setEditable(false);
                jTextFieldDataEntrada.setEditable(false);
                jTextFieldDataInicioVigencia.setEditable(false);
                jTextFieldGrupo.setEditable(false);
                jTextFieldNomeAdmin.setEditable(false);
                jTextFieldNomeCliente.setEditable(false);
                jTextFieldNomeModelo.setEditable(false);
                jTextFieldNomeVendedor.setEditable(false);
                jTextFieldNumeroContrato.setEditable(false);
                jTextFieldObservacao.setEditable(false);
                jTextFieldQuantidadeParcela.setEditable(false);
                jTextFieldValorBem.setEditable(false);
                jTextFieldValorEntrada.setEditable(false);
                break;
            case 4:
                // inserir dados
                
                iniciarView();
                break;

            case 5:
                // alterar dados
                
                iniciarView();
                break;
        }
    }//GEN-LAST:event_jButtonConfirmarMouseClicked

    private void jButtonInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInserirMouseClicked
        // TODO add your handling code here:
        acao = 4; //inserir

        jButtonConsultar.setEnabled(false);
        jButtonInserir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonConfirmar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldCodigoAdmin.setText("");
        jTextFieldCodigoCliente.setText("");
        jTextFieldCodigoModelo.setText("");
        jTextFieldCodigoVenda.setText("");
        jTextFieldCodigoVendedor.setText("");
        jTextFieldCota.setText("");
        jTextFieldDataCadastral.setText("");
        jTextFieldDataEntrada.setText("");
        jTextFieldDataInicioVigencia.setText("");
        jTextFieldGrupo.setText("");
        jTextFieldNomeAdmin.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldNomeModelo.setText("");
        jTextFieldNomeVendedor.setText("");
        jTextFieldNumeroContrato.setText("");
        jTextFieldObservacao.setText("");
        jTextFieldQuantidadeParcela.setText("");
        jTextFieldValorBem.setText("");
        jTextFieldValorEntrada.setText("");

        jTextFieldCodigoAdmin.setEnabled(true);
        jTextFieldCodigoCliente.setEnabled(true);
        jTextFieldCodigoModelo.setEnabled(true);
        jTextFieldCodigoVenda.setEnabled(true);
        jTextFieldCodigoVendedor.setEnabled(true);
        jTextFieldCota.setEnabled(true);
        jTextFieldDataCadastral.setEnabled(true);
        jTextFieldDataEntrada.setEnabled(true);
        jTextFieldDataInicioVigencia.setEnabled(true);
        jTextFieldGrupo.setEnabled(true);
        jTextFieldNomeAdmin.setEnabled(true);
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldNomeModelo.setEnabled(true);
        jTextFieldNomeVendedor.setEnabled(true);
        jTextFieldNumeroContrato.setEnabled(true);
        jTextFieldObservacao.setEnabled(true);
        jTextFieldQuantidadeParcela.setEnabled(true);
        jTextFieldValorBem.setEnabled(true);
        jTextFieldValorEntrada.setEnabled(true);

        jTextFieldCodigoAdmin.setEditable(true);
        jTextFieldCodigoCliente.setEditable(true);
        jTextFieldCodigoModelo.setEditable(true);
        jTextFieldCodigoVenda.setEditable(true);
        jTextFieldCodigoVendedor.setEditable(true);
        jTextFieldCota.setEditable(true);
        jTextFieldDataCadastral.setEditable(true);
        jTextFieldDataEntrada.setEditable(true);
        jTextFieldDataInicioVigencia.setEditable(true);
        jTextFieldGrupo.setEditable(true);
        jTextFieldNomeAdmin.setEditable(true);
        jTextFieldNomeCliente.setEditable(true);
        jTextFieldNomeModelo.setEditable(true);
        jTextFieldNomeVendedor.setEditable(true);
        jTextFieldNumeroContrato.setEditable(true);
        jTextFieldObservacao.setEditable(true);
        jTextFieldQuantidadeParcela.setEditable(true);
        jTextFieldValorBem.setEditable(true);
        jTextFieldValorEntrada.setEditable(true);
    }//GEN-LAST:event_jButtonInserirMouseClicked

    private void jButtonAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarMouseClicked
        // TODO add your handling code here:
        acao = 5; //alterar

        jButtonConsultar.setEnabled(false);
        jButtonInserir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonConfirmar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldCodigoAdmin.setEditable(true);
        jTextFieldCodigoCliente.setEditable(true);
        jTextFieldCodigoModelo.setEditable(true);
        jTextFieldCodigoVenda.setEditable(true);
        jTextFieldCodigoVendedor.setEditable(true);
        jTextFieldCota.setEditable(true);
        jTextFieldDataCadastral.setEditable(true);
        jTextFieldDataEntrada.setEditable(true);
        jTextFieldDataInicioVigencia.setEditable(true);
        jTextFieldGrupo.setEditable(true);
        jTextFieldNomeAdmin.setEditable(true);
        jTextFieldNomeCliente.setEditable(true);
        jTextFieldNomeModelo.setEditable(true);
        jTextFieldNomeVendedor.setEditable(true);
        jTextFieldNumeroContrato.setEditable(true);
        jTextFieldObservacao.setEditable(true);
        jTextFieldQuantidadeParcela.setEditable(true);
        jTextFieldValorBem.setEditable(true);
        jTextFieldValorEntrada.setEditable(true);        
    }//GEN-LAST:event_jButtonAlterarMouseClicked

    private void jButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Confirma a exclusão da Venda???", "Excluir", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(null, "Venda Excluída!!!");
            
            iniciarView();
        }
    }//GEN-LAST:event_jButtonExcluirMouseClicked

    private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseClicked
        // TODO add your handling code here:
        sairView();
    }//GEN-LAST:event_jButtonSairMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCota;
    private javax.swing.JLabel jLabelDataCadastral;
    private javax.swing.JLabel jLabelDataEntrada;
    private javax.swing.JLabel jLabelDataInicioVigencia;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNumeroContrato;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelQuatidadeParcela;
    private javax.swing.JLabel jLabelValorBem;
    private javax.swing.JLabel jLabelValorEntrada;
    private javax.swing.JLabel jLabelVenda;
    private javax.swing.JLabel jLabelVendedor;
    private javax.swing.JTextField jTextFieldCodigoAdmin;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldCodigoModelo;
    private javax.swing.JTextField jTextFieldCodigoVenda;
    private javax.swing.JTextField jTextFieldCodigoVendedor;
    private javax.swing.JTextField jTextFieldCota;
    private javax.swing.JTextField jTextFieldDataCadastral;
    private javax.swing.JTextField jTextFieldDataEntrada;
    private javax.swing.JTextField jTextFieldDataInicioVigencia;
    private javax.swing.JTextField jTextFieldGrupo;
    private javax.swing.JTextField jTextFieldNomeAdmin;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNomeModelo;
    private javax.swing.JTextField jTextFieldNomeVendedor;
    private javax.swing.JTextField jTextFieldNumeroContrato;
    private javax.swing.JTextField jTextFieldObservacao;
    private javax.swing.JTextField jTextFieldQuantidadeParcela;
    private javax.swing.JTextField jTextFieldValorBem;
    private javax.swing.JTextField jTextFieldValorEntrada;
    // End of variables declaration//GEN-END:variables
}
